spring:
  application:
    name: Produtos API - (Spring Boot - Primeiros Passos)
  datasource:
    url: jdbc:h2:mem:produtos
    username: sa
    password: adminadmin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console